// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw-YnleHGXgHYVdck8EmZdy-RBYjMMm2w',
    appId: '1:705998604868:web:e6e97856c202ae08040a11',
    messagingSenderId: '705998604868',
    projectId: 'referal-app-d802f',
    authDomain: 'referal-app-d802f.firebaseapp.com',
    storageBucket: 'referal-app-d802f.appspot.com',
    measurementId: 'G-JWBMB69YPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTD3zchTgkzC8YDkWlQIYULgUrR4F8avI',
    appId: '1:705998604868:android:a70332b896f7dacd040a11',
    messagingSenderId: '705998604868',
    projectId: 'referal-app-d802f',
    storageBucket: 'referal-app-d802f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9-AjByIqw3d5wS4WLCICVJsx_m2G_KDg',
    appId: '1:705998604868:ios:1e081878e20d42b5040a11',
    messagingSenderId: '705998604868',
    projectId: 'referal-app-d802f',
    storageBucket: 'referal-app-d802f.appspot.com',
    iosBundleId: 'com.example.refApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9-AjByIqw3d5wS4WLCICVJsx_m2G_KDg',
    appId: '1:705998604868:ios:d0ce525a66eeb3de040a11',
    messagingSenderId: '705998604868',
    projectId: 'referal-app-d802f',
    storageBucket: 'referal-app-d802f.appspot.com',
    iosBundleId: 'com.example.refApp.RunnerTests',
  );
}
