// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATUvojx3Kde_84bKiDC7RD_dJi87WCKow',
    appId: '1:219516150336:web:483e585f59e22eb56635a5',
    messagingSenderId: '219516150336',
    projectId: 'referal-1',
    authDomain: 'referal-1.firebaseapp.com',
    storageBucket: 'referal-1.appspot.com',
    measurementId: 'G-62ZDR6YSGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATxnOvkIilF7GNvUUQsw-dNw5cZviwnLg',
    appId: '1:219516150336:android:1e30e52e979a39146635a5',
    messagingSenderId: '219516150336',
    projectId: 'referal-1',
    storageBucket: 'referal-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGAzME81kYoH6T215wvoFqhC7FsO-RdiU',
    appId: '1:219516150336:ios:d3bc28fc83fceec76635a5',
    messagingSenderId: '219516150336',
    projectId: 'referal-1',
    storageBucket: 'referal-1.appspot.com',
    iosBundleId: 'com.example.refApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGAzME81kYoH6T215wvoFqhC7FsO-RdiU',
    appId: '1:219516150336:ios:dae2fc4bb959f55a6635a5',
    messagingSenderId: '219516150336',
    projectId: 'referal-1',
    storageBucket: 'referal-1.appspot.com',
    iosBundleId: 'com.example.refApp.RunnerTests',
  );
}
