// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtJZk-E0Z_qkw8xer5_a6PTdqgxfvZmRo',
    appId: '1:795160752516:web:01289896ffb8017cc7add1',
    messagingSenderId: '795160752516',
    projectId: 'mychatapp2023',
    authDomain: 'mychatapp2023.firebaseapp.com',
    storageBucket: 'mychatapp2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1K3qldx2Fa8oNbPSFs9i9-nUFNHQm0q0',
    appId: '1:795160752516:android:c5a96bfe5ace1bc4c7add1',
    messagingSenderId: '795160752516',
    projectId: 'mychatapp2023',
    storageBucket: 'mychatapp2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGjqmQyD73Li8KPg__6fULsCw6VjFX6I',
    appId: '1:795160752516:ios:d8d44ef7b9d4f802c7add1',
    messagingSenderId: '795160752516',
    projectId: 'mychatapp2023',
    storageBucket: 'mychatapp2023.appspot.com',
    iosBundleId: 'com.example.oop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGjqmQyD73Li8KPg__6fULsCw6VjFX6I',
    appId: '1:795160752516:ios:72a7da73d32c7d96c7add1',
    messagingSenderId: '795160752516',
    projectId: 'mychatapp2023',
    storageBucket: 'mychatapp2023.appspot.com',
    iosBundleId: 'com.example.oop.RunnerTests',
  );
}
