// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRi_OHR_E13zmOdpUH2dSqdVeYu3rHGk',
    appId: '1:449785277084:web:bcf6f5fba7650abcdf1b59',
    messagingSenderId: '449785277084',
    projectId: 'mychat-73260',
    authDomain: 'mychat-73260.firebaseapp.com',
    storageBucket: 'mychat-73260.appspot.com',
    measurementId: 'G-ZZNG1BL1HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHRkyd9VwjkSZWo4zBhdUC4SV_6tiU8Q',
    appId: '1:449785277084:android:62f6df006d65c458df1b59',
    messagingSenderId: '449785277084',
    projectId: 'mychat-73260',
    storageBucket: 'mychat-73260.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKuIUFq9k1l9DgBbL6d0ahEiDYUDH_Xj8',
    appId: '1:449785277084:ios:b714e1e6ce3e2b73df1b59',
    messagingSenderId: '449785277084',
    projectId: 'mychat-73260',
    storageBucket: 'mychat-73260.appspot.com',
    iosBundleId: 'com.example.flashChats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKuIUFq9k1l9DgBbL6d0ahEiDYUDH_Xj8',
    appId: '1:449785277084:ios:6422fd58d10a9dd6df1b59',
    messagingSenderId: '449785277084',
    projectId: 'mychat-73260',
    storageBucket: 'mychat-73260.appspot.com',
    iosBundleId: 'com.example.flashChats.RunnerTests',
  );
}
