// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9IjT2aZCZDA07QGH2Pbv7TZNnBTEky1Y',
    appId: '1:527744312575:web:84d5125b3fe70742be98ca',
    messagingSenderId: '527744312575',
    projectId: 'referal2-97578',
    authDomain: 'referal2-97578.firebaseapp.com',
    storageBucket: 'referal2-97578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEXKfbaVUzDjLr4hEMGQqVl_SOeksH0qk',
    appId: '1:527744312575:android:c278be1063db6936be98ca',
    messagingSenderId: '527744312575',
    projectId: 'referal2-97578',
    storageBucket: 'referal2-97578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzX6JyrKe0W4J2kR-uBfoOFcHaSof8cnE',
    appId: '1:527744312575:ios:7cbe426d265c8ebdbe98ca',
    messagingSenderId: '527744312575',
    projectId: 'referal2-97578',
    storageBucket: 'referal2-97578.appspot.com',
    iosBundleId: 'com.example.referalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzX6JyrKe0W4J2kR-uBfoOFcHaSof8cnE',
    appId: '1:527744312575:ios:620e3a7ccf4970e5be98ca',
    messagingSenderId: '527744312575',
    projectId: 'referal2-97578',
    storageBucket: 'referal2-97578.appspot.com',
    iosBundleId: 'com.example.referalApp.RunnerTests',
  );
}
