// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0weUx224NCh8yOJG63zoaqou3PxUagjk',
    appId: '1:723846073888:web:e96944f202c6e09e3b3645',
    messagingSenderId: '723846073888',
    projectId: 'pollls-app',
    authDomain: 'pollls-app.firebaseapp.com',
    storageBucket: 'pollls-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nzpxSgSGnJaowp0YWZlGHHXC7ycxuvA',
    appId: '1:723846073888:android:f6d8c0f2a867c2af3b3645',
    messagingSenderId: '723846073888',
    projectId: 'pollls-app',
    storageBucket: 'pollls-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIob9pWfaKpGLP9mx3DPXB2F9oiOWepKI',
    appId: '1:723846073888:ios:658db8f721679a553b3645',
    messagingSenderId: '723846073888',
    projectId: 'pollls-app',
    storageBucket: 'pollls-app.appspot.com',
    iosBundleId: 'com.example.polls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIob9pWfaKpGLP9mx3DPXB2F9oiOWepKI',
    appId: '1:723846073888:ios:239598074d1038bb3b3645',
    messagingSenderId: '723846073888',
    projectId: 'pollls-app',
    storageBucket: 'pollls-app.appspot.com',
    iosBundleId: 'com.example.polls.RunnerTests',
  );
}
