// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGYc3LOib8_JyFdOup0DR06MLx4skvoyk',
    appId: '1:285062319108:web:e5413f1c14b869fb327951',
    messagingSenderId: '285062319108',
    projectId: 'fir-firestore-fd411',
    authDomain: 'fir-firestore-fd411.firebaseapp.com',
    storageBucket: 'fir-firestore-fd411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwdKuaPz-iXAQRLhk6P_Fn28vUZimrAM',
    appId: '1:285062319108:android:639fa5bf296b5a66327951',
    messagingSenderId: '285062319108',
    projectId: 'fir-firestore-fd411',
    storageBucket: 'fir-firestore-fd411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_BMSnFTQcZak_KO9plnqiWxc0ZQj0MTI',
    appId: '1:285062319108:ios:47541c9625c5ed19327951',
    messagingSenderId: '285062319108',
    projectId: 'fir-firestore-fd411',
    storageBucket: 'fir-firestore-fd411.appspot.com',
    iosBundleId: 'com.example.firebaseFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_BMSnFTQcZak_KO9plnqiWxc0ZQj0MTI',
    appId: '1:285062319108:ios:ced0dd536562f3c4327951',
    messagingSenderId: '285062319108',
    projectId: 'fir-firestore-fd411',
    storageBucket: 'fir-firestore-fd411.appspot.com',
    iosBundleId: 'com.example.firebaseFirestore.RunnerTests',
  );
}
